apiVersion: v1
kind: Service
metadata:
  name: my-python-app
spec:
  type: NodePort
  selector:
    app: my-python-app
  ports:
    - protocol: TCP
      port: 8000 # Port exposed internally within the cluster
      targetPort: 8000 # Port on the container where the application listens
      nodePort: 30800
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: my-python-container
        imagePullPolicy: Never
        image: python:test2 # 직접 빌드한 도커 이미지 이름으로 변경해야 합니다.
        command: ["gunicorn", "-w", "4", "-k", "gevent", "--bind", "0.0.0.0:8000", "--timeout", "10", "--log-level", "debug", "--access-logfile", "-", "app:app"]
        ports:
        - containerPort: 8000
        env:
        - name: WAIT_TIME
          value: "20" # app.py의 wait_time을 20초로 설정
        - name: TIMEOUT
          value: "10" # Gunicorn의 timeout을 60초로 설정
        - name: KEEP_ALIVE
          value: "10" # Gunicorn의 keep-alive를 10초로 설정